services:
- type: web
  env: node
  name: hyper63-play
  disk:
    name: hyper63-play-disk
    mountPath: /data
    sizeGB: 10
  startCommand: yarn start
  buildCommand: yarn && yarn upgrade && cd web && yarn && yarn build
  envVars:
    - key: DATA
      value: /data
    - key: SECRET
      generateValue: true
    - key: ELASTIC_APM_SERVICE_NAME
      value: hyper-playground
    - key: ELASTIC_APM_SECRET_TOKEN
      sync: false
    - key: ELASTIC_APM_SERVER_URL
      value: https://hyper.apm.us-west-2.aws.found.io

  
